export _BASE_PATH="RawDataset"
export _PROC_PATH="ProcessedDataset"
export _PROC_LUC_VAN_TIEN_PATH="$_PROC_PATH/LucVanTien"
export _PROC_TALE_OF_KIEU_1866_PATH="$_PROC_PATH/TaleOfKieu1866"
export _PROC_TALE_OF_KIEU_1871_PATH="$_PROC_PATH/TaleOfKieu1871"
export _PROC_TALE_OF_KIEU_1902_PATH="$_PROC_PATH/TaleOfKieu1902"
export _LUC_VAN_TIEN_IMAGES_PATH="$_BASE_PATH/Luc Van Tien/lvt-raw-images"
export _LUC_VAN_TIEN_LABELS_PATH="$_BASE_PATH/Luc Van Tien/lvt-mynom"
export _TALE_OF_KIEU_1866_IMAGES_PATH="$_BASE_PATH/Tale of Kieu/1866-raw-images"
export _TALE_OF_KIEU_1866_LABELS_PATH="$_BASE_PATH/Tale of Kieu/1866-mynom"
export _TALE_OF_KIEU_1871_IMAGES_PATH="$_BASE_PATH/Tale of Kieu/1871-raw-images"
export _TALE_OF_KIEU_1871_LABELS_PATH="$_BASE_PATH/Tale of Kieu/1871-mynom"
export _TALE_OF_KIEU_1902_IMAGES_PATH="$_BASE_PATH/Tale of Kieu/1902-raw-images"
export _TALE_OF_KIEU_1902_LABELS_PATH="$_BASE_PATH/Tale of Kieu/1902-mynom"
export _LEFT_COOR_NAME="LEFT"
export _RIGHT_COOR_NAME="RIGHT"
export _TOP_COOR_NAME="TOP"
export _BOTTOM_COOR_NAME="BOTTOM"
export _LABEL_NAME="UNICODE"
export _UNKNOWN_CHARACTER="UNK"
export _LABEL_NAME_TALE_OF_KIEU_1866="UNICODE1"
export _CONFIDENCE_NAME_TALE_OF_KIEU_1866="CONFIDENCE1"
export _CONFIDENCE_THRESHOLD=0.9
export _WIDTH_SCALED=44
export _HEIGHT_SCALED=44

clearenv () {
    unset _BASE_PATH
    unset _PROC_PATH
    unset _PROC_LUC_VAN_TIEN_PATH
    unset _PROC_TALE_OF_KIEU_1866_PATH
    unset _PROC_TALE_OF_KIEU_1871_PATH
    unset _PROC_TALE_OF_KIEU_1902_PATH
    unset _LUC_VAN_TIEN_IMAGES_PATH
    unset _LUC_VAN_TIEN_LABELS_PATH
    unset _TALE_OF_KIEU_1866_IMAGES_PATH
    unset _TALE_OF_KIEU_1866_LABELS_PATH
    unset _TALE_OF_KIEU_1871_IMAGES_PATH
    unset _TALE_OF_KIEU_1871_LABELS_PATH
    unset _TALE_OF_KIEU_1902_IMAGES_PATH
    unset _TALE_OF_KIEU_1902_LABELS_PATH
    unset _LEFT_COOR_NAME
    unset _RIGHT_COOR_NAME
    unset _TOP_COOR_NAME
    unset _BOTTOM_COOR_NAME
    unset _LABEL_NAME
    unset _UNKNOWN_CHARACTER
    unset _LABEL_NAME_TALE_OF_KIEU_1866
    unset _CONFIDENCE_NAME_TALE_OF_KIEU_1866
    unset _CONFIDENCE_THRESHOLD
    unset _WIDTH_SCALED
    unset _HEIGHT_SCALED
}
