export _BASE_PATH="RawDataset"
export _PROC_PATH="NomCharacters"
export _LUC_VAN_TIEN_IMAGES_PATH="$_BASE_PATH/Luc Van Tien/lvt-raw-images"
export _LUC_VAN_TIEN_LABELS_PATH="$_BASE_PATH/Luc Van Tien/lvt-mynom"
export _TALE_OF_KIEU_1866_IMAGES_PATH="$_BASE_PATH/Tale of Kieu/1866-raw-images"
export _TALE_OF_KIEU_1866_LABELS_PATH="$_BASE_PATH/Tale of Kieu/1866-mynom"
export _TALE_OF_KIEU_1871_IMAGES_PATH="$_BASE_PATH/Tale of Kieu/1871-raw-images"
export _TALE_OF_KIEU_1871_LABELS_PATH="$_BASE_PATH/Tale of Kieu/1871-mynom"
export _TALE_OF_KIEU_1902_IMAGES_PATH="$_BASE_PATH/Tale of Kieu/1902-raw-images"
export _TALE_OF_KIEU_1902_LABELS_PATH="$_BASE_PATH/Tale of Kieu/1902-mynom"
export _LEFT_COOR_NAME="LEFT"
export _RIGHT_COOR_NAME="RIGHT"
export _TOP_COOR_NAME="TOP"
export _BOTTOM_COOR_NAME="BOTTOM"
export _LABEL_NAME="UNICODE"
export _UNKNOWN_CHARACTER="UNK"
export _LABEL_NAME_TALE_OF_KIEU_1866="UNICODE1"
export _CONFIDENCE_NAME_TALE_OF_KIEU_1866="CONFIDENCE1"
export _CONFIDENCE_THRESHOLD=0.9
export _WIDTH_SCALED=44
export _HEIGHT_SCALED=44
export _CHARACTER_FILE_EXTENSION="png"
export _RAW_IMAGE_FILE_EXTENSION="jpg"
export _RAW_LABEL_FILE_EXTENSION="xlsx"
export _META_DATA_FILE_NAME="meta_data.yaml"

clearenv () {
    unset _BASE_PATH
    unset _PROC_PATH
    unset _LUC_VAN_TIEN_IMAGES_PATH
    unset _LUC_VAN_TIEN_LABELS_PATH
    unset _TALE_OF_KIEU_1866_IMAGES_PATH
    unset _TALE_OF_KIEU_1866_LABELS_PATH
    unset _TALE_OF_KIEU_1871_IMAGES_PATH
    unset _TALE_OF_KIEU_1871_LABELS_PATH
    unset _TALE_OF_KIEU_1902_IMAGES_PATH
    unset _TALE_OF_KIEU_1902_LABELS_PATH
    unset _LEFT_COOR_NAME
    unset _RIGHT_COOR_NAME
    unset _TOP_COOR_NAME
    unset _BOTTOM_COOR_NAME
    unset _LABEL_NAME
    unset _UNKNOWN_CHARACTER
    unset _LABEL_NAME_TALE_OF_KIEU_1866
    unset _CONFIDENCE_NAME_TALE_OF_KIEU_1866
    unset _CONFIDENCE_THRESHOLD
    unset _WIDTH_SCALED
    unset _HEIGHT_SCALED
    unset _CHARACTER_FILE_EXTENSION
    unset _RAW_IMAGE_FILE_EXTENSION
    unset _RAW_LABEL_FILE_EXTENSION
    unset _META_DATA_FILE_NAME
}
