export _BASE_PATH="RawDataset"
export _PROC_PATH="NomCharacters"
export _CHARACTER_FILE_EXTENSION="png"
export _META_DATA_FILE_NAME="meta_data.yaml"

export _AUGMENTED_IMAGE_ALIAS="aug"

export _TRAIN_SPLIT_NAME="train"
export _VAL_SPLIT_NAME="val"
export _TEST_SPLIT_NAME="test"

export _META_LEARNING_DATASET_PATH="MetaLearningDataset"
export _META_TRAIN_PATH="$_META_LEARNING_DATASET_PATH/$_TRAIN_SPLIT_NAME"
export _META_VAL_PATH="$_META_LEARNING_DATASET_PATH/$_VAL_SPLIT_NAME"
export _META_TEST_PATH="$_META_LEARNING_DATASET_PATH/$_TEST_SPLIT_NAME"

export _TRANSFER_LEARNING_DATASET_PATH="TransferLearningDataset"
export _PRE_TRAIN_PATH="$_TRANSFER_LEARNING_DATASET_PATH/pre_train"
export _FINE_TUNE_PATH="$_TRANSFER_LEARNING_DATASET_PATH/fine_tune"
export _PRE_TRAIN_TRAIN_PATH="$_PRE_TRAIN_PATH/$_TRAIN_SPLIT_NAME"
export _PRE_TRAIN_VAL_PATH="$_PRE_TRAIN_PATH/$_VAL_SPLIT_NAME"
export _PRE_TRAIN_TEST_PATH="$_PRE_TRAIN_PATH/$_TEST_SPLIT_NAME"
export _FINE_TUNE_TRAIN_PATH="$_FINE_TUNE_PATH/$_TRAIN_SPLIT_NAME"
export _FINE_TUNE_VAL_PATH="$_FINE_TUNE_PATH/$_VAL_SPLIT_NAME"
export _FINE_TUNE_TEST_PATH="$_FINE_TUNE_PATH/$_TEST_SPLIT_NAME"

export _SAVE_INTERVAL=100
export _PRINT_INTERVAL=10
export _VAL_INTERVAL=100
export _NUM_TEST_TASKS=600


clearenv () {
    unset _BASE_PATH
    unset _PROC_PATH
    unset _CHARACTER_FILE_EXTENSION
    unset _META_DATA_FILE_NAME

    unset _AUGMENTED_IMAGE_ALIAS

    unset _TRAIN_SPLIT_NAME
    unset _VAL_SPLIT_NAME
    unset _TEST_SPLIT_NAME

    unset _META_LEARNING_DATASET_PATH
    unset _META_TRAIN_PATH
    unset _META_VAL_PATH
    unset _META_TEST_PATH

    unset _TRANSFER_LEARNING_DATASET_PATH
    unset _PRE_TRAIN_PATH
    unset _FINE_TUNE_PATH
    unset _PRE_TRAIN_TRAIN_PATH
    unset _PRE_TRAIN_VAL_PATH
    unset _PRE_TRAIN_TEST_PATH
    unset _FINE_TUNE_TRAIN_PATH
    unset _FINE_TUNE_VAL_PATH
    unset _FINE_TUNE_TEST_PATH

    unset _SAVE_INTERVAL
    unset _PRINT_INTERVAL
    unset _VAL_INTERVAL
    unset _NUM_TEST_TASKS
}
